services:
  jenkins:
    build:
      context: .
    image: jenkins/jenkins:lts
    container_name: flowlink-jenkins
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"

volumes:
  jenkins_home:
    driver: local